In [1]:
import talib as ta
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pandas_datareader as web
import datetime as dt
import mplfinance as mpf
import yfinance as yf
from myTA import downloadAndMakeAnalysis, makeAnalysis, plotAnalysis, Portfolio, Trade, calculateProfit, TradingStrategies

c:\Users\QbaSo\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "

In [2]:
tickers = pd.read_csv("nasdaqTickers.csv")

In [3]:
tickers

,Symbol,Name,Last Sale,Net Change,% Change,Market Cap,Country,IPO Year,Volume,Sector,Industry
0,A,Agilent Technologies Inc. Common Stock,$149.65,-1.4400,-0.953%,4.430718e+10,United States,1999.0,699759,Industrials,Electrical Products
1,AA,Alcoa Corporation Common Stock,$45.47,-1.0900,-2.341%,8.045333e+09,NaN,2016.0,3584741,Industrials,Metal Fabrications
2,AAC,Ares Acquisition Corporation Class A Ordinary ...,$10.07,-0.0200,-0.198%,1.258750e+09,NaN,2021.0,213355,Finance,Business Services
3,AACG,ATA Creativity Global American Depositary Shares,$1.2733,-0.0767,-5.681%,3.995223e+07,China,2008.0,14435,Consumer Discretionary,Service to the Health Industry
4,AACI,Armada Acquisition Corp. I Common Stock,$10.12,0.0200,0.198%,2.095801e+08,United States,2021.0,20672,Industrials,Consumer Electronics/Appliances
...,...,...,...,...,...,...,...,...,...,...,...
8053,ZVSA,ZyVersa Therapeutics Inc. Common Stock,$1.57,0.0200,1.29%,1.425862e+07,United States,2022.0,45625,Health Care,Biotechnology: Pharmaceutical Preparations
8054,ZWS,Zurn Elkay Water Solutions Corporation Common ...,$21.15,-0.6600,-3.026%,3.760356e+09,United States,2012.0,890354,Utilities,Environmental Services
8055,ZYME,Zymeworks Inc. Common Stock,$7.86,0.0500,0.64%,4.951510e+08,United States,NaN,362492,Health Care,Biotechnology: Biological Products (No Diagnos...
8056,ZYNE,Zynerba Pharmaceuticals Inc. Common Stock,$0.53,-0.0369,-6.509%,2.494324e+07,United States,2015.0,470618,Health Care,Biotechnology: Pharmaceutical Preparations
8057,ZYXI,Zynex Inc. Common Stock,$13.91,0.0400,0.288%,5.355350e+08,United States,NaN,235576,Health Care,Other Pharmaceuticals

# Download a lot of historical data

In [4]:
delisted = []

for i in range(10):
    code=tickers['Symbol'][i]
    try:
        df = downloadAndMakeAnalysis(code, dt.datetime(1980,1,1), dt.datetime.now(),'1d').reset_index()
        df.to_csv(f"E:/Datasets/Stock/{code}.csv")
    except:
        delisted.append(i)

1 Failed download:
- AAIC^B: No data found, symbol may be delisted

1 Failed download:
- AAIC^C: No data found, symbol may be delisted

In [5]:
df

,Date,Open,High,Low,Close,Adj Close,Volume,RSI,macd,macd_signal,macd_hist,SMA200,SMA100
0,2021-07-19,24.750000,24.790001,24.600000,24.740000,22.856573,89600,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-07-20,24.850000,24.850000,24.650000,24.757000,22.872280,16800,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-07-21,24.799999,24.799999,24.730000,24.770000,22.884289,36700,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-07-22,24.770000,24.799999,24.740000,24.770000,22.884289,24400,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-07-23,24.780001,24.780001,24.730000,24.750000,22.865812,16900,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
363,2022-12-23,23.459999,23.500000,23.440001,23.440001,23.440001,500,54.305627,0.032391,-0.011060,0.043451,23.955075,23.54138
364,2022-12-27,23.179001,23.480000,23.179001,23.480000,23.480000,900,55.097323,0.046205,0.000393,0.045812,23.947725,23.53818
365,2022-12-28,23.490000,23.500000,23.490000,23.500000,23.500000,1500,55.512382,0.058097,0.011934,0.046163,23.941175,23.53358
366,2022-12-29,23.469999,23.469999,23.469999,23.469999,23.469999,300,54.695674,0.064359,0.022419,0.041940,23.934475,23.52908
367,2022-12-30,23.500000,23.500000,23.500000,23.500000,23.500000,500,55.402275,0.070925,0.032120,0.038805,23.927475,23.52438

In [6]:
df = downloadAndMakeAnalysis('AAIC^B', dt.datetime(1980,1,1), dt.datetime.now(),'1d').reset_index()

1 Failed download:
- AAIC^B: No data found, symbol may be delisted

Exception: inputs are all NaN